apply plugin: 'maven-publish'

def VERSION_NAME = "0.0.1"// 版本

javadoc {
    options.addStringOption("charset", "UTF-8")
    if (JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
}

//远程发布， 发布到我自己的私有库
afterEvaluate {
    publishing {
        publications {
            maven(MavenPublication) {
                //from javadoc.destinationDir
                //from sourceSets.main.allSource
                from components.java

                groupId = "io.github.mahongyin.${rootProject.projectDir.name}"
                artifactId = projectDir.name
                version = VERSION_NAME
                description "lib is a auth with comon"
            }
        }

        repositories {
            maven {
                //name 'mavenCentral'
                url "./repo"//"https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
//                credentials {
//                    username mavenCentralUsername
//                    password mavenCentralPassword
//                }
            }
        }
    }
}