allprojects {
	apply plugin: 'java'
	apply plugin: 'idea'
	
	group = 'org.nanohttpd'
	version = '2.3.5-SNAPSHOT'
}

subprojects {
	apply plugin: 'java'
	sourceCompatibility = JavaVersion.VERSION_1_7
	targetCompatibility = JavaVersion.VERSION_1_7
	
	repositories {
		mavenCentral()
		jcenter()
	}
	
	dependencies {
		testCompile group: 'junit', name: 'junit', version: '4.12'
	}
}