
description = 'NanoHttpd-Core'

dependencies {
	testCompile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.13'
	testCompile group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.5.13'
}



//apply from: "../upload.gradle"
apply from: "../artifactory.gradle"
//apply from: "../jitpack.gradle"