description = 'NanoHttpd-Core'

dependencies {
	testCompile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.13'
	testCompile group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.5.13'
}

task wrapper(type: Wrapper) {
	gradleVersion = "4.4.1"
}

//apply from: "../upload.gradle"
//apply from: "../jitpack.gradle"
//发布到artifactory
apply from: "../artifactory.gradle"